# Generated by Django 2.2.14 on 2020-07-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoursrange',
            name='open_time',
        ),
        migrations.AddField(
            model_name='hoursrange',
            name='open_times',
            field=models.ManyToManyField(related_name='hours_ranges', to='stores.OpenTime'),
        ),
    ]
