# Generated by Django 2.2.14 on 2020-07-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20200718_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='code',
            field=models.CharField(default='COCO1223556', max_length=25, unique=True),
            preserve_default=False,
        ),
    ]
