# Generated by Django 2.2.14 on 2020-07-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_voucher_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='max_units',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='min_units',
            field=models.IntegerField(default=0),
        ),
    ]
